name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: macos-15
            target: aarch64-apple-darwin
            folder: darwin-arm64
          - host: macos-15
            target: x86_64-apple-darwin
            folder: darwin-x64
          - host: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            folder: linux-x64-gnu
          - host: windows-2025
            target: x86_64-pc-windows-msvc
            folder: win32-x64-msvc
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: npm install -g npm@latest
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: pnpm install
      - run: pnpm napi build --platform --release --esm --target ${{ matrix.target }}

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: nodes-${{ matrix.target }}
          path: |
            *.node
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          pattern: nodes-*
          merge-multiple: true
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: npm install -g npm@latest
      - run: pnpm install
      - run: pnpm napi create-npm-dirs
      - run: pnpm napi artifacts -o .
      - run: node scripts/binaries.mjs
      - run: pnpm publish --no-git-checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
